export const countries: { code: string; name: string }[] = [
  { code: 'unknown', name: 'countryUnknown' }, // Key for translation
  { code: 'Afghanistan', name: 'Afghanistan' },
  { code: 'Albania', name: 'Albania' },
  { code: 'Algeria', name: 'Algeria' },
  { code: 'Andorra', name: 'Andorra' },
  { code: 'Angola', name: 'Angola' },
  { code: 'Antigua and Barbuda', name: 'Antigua and Barbuda' },
  { code: 'Argentina', name: 'Argentina' },
  { code: 'Armenia', name: 'Armenia' },
  { code: 'Australia', name: 'Australia' },
  { code: 'Austria', name: 'Austria' },
  { code: 'Azerbaijan', name: 'Azerbaijan' },
  { code: 'Bahamas', name: 'Bahamas' },
  { code: 'Bahrain', name: 'Bahrain' },
  { code: 'Bangladesh', name: 'Bangladesh' },
  { code: 'Barbados', name: 'Barbados' },
  { code: 'Belarus', name: 'Belarus' },
  { code: 'Belgium', name: 'Belgium' },
  { code: 'Belize', name: 'Belize' },
  { code: 'Benin', name: 'Benin' },
  { code: 'Bhutan', name: 'Bhutan' },
  { code: 'Bolivia', name: 'Bolivia' },
  { code: 'Bosnia and Herzegovina', name: 'Bosnia and Herzegovina' },
  { code: 'Botswana', name: 'Botswana' },
  { code: 'Brazil', name: 'Brazil' },
  { code: 'Brunei', name: 'Brunei' },
  { code: 'Bulgaria', name: 'Bulgaria' },
  { code: 'Burkina Faso', name: 'Burkina Faso' },
  { code: 'Burundi', name: 'Burundi' },
  { code: 'Cabo Verde', name: 'Cabo Verde' },
  { code: 'Cambodia', name: 'Cambodia' },
  { code: 'Cameroon', name: 'Cameroon' },
  { code: 'Canada', name: 'Canada' },
  { code: 'Central African Republic', name: 'Central African Republic' },
  { code: 'Chad', name: 'Chad' },
  { code: 'Chile', name: 'Chile' },
  { code: 'China', name: 'China' },
  { code: 'Colombia', name: 'Colombia' },
  { code: 'Comoros', name: 'Comoros' },
  { code: 'Congo, Democratic Republic of the', name: 'Congo, Democratic Republic of the' },
  { code: 'Congo, Republic of the', name: 'Congo, Republic of the' },
  { code: 'Costa Rica', name: 'Costa Rica' },
  { code: 'Croatia', name: 'Croatia' },
  { code: 'Cuba', name: 'Cuba' },
  { code: 'Cyprus', name: 'Cyprus' },
  { code: 'Czech Republic', name: 'Czech Republic' },
  { code: 'Denmark', name: 'Denmark' },
  { code: 'Djibouti', name: 'Djibouti' },
  { code: 'Dominica', name: 'Dominica' },
  { code: 'Dominican Republic', name: 'Dominican Republic' },
  { code: 'Ecuador', name: 'Ecuador' },
  { code: 'Egypt', name: 'Egypt' },
  { code: 'El Salvador', name: 'El Salvador' },
  { code: 'Equatorial Guinea', name: 'Equatorial Guinea' },
  { code: 'Eritrea', name: 'Eritrea' },
  { code: 'Estonia', name: 'Estonia' },
  { code: 'Eswatini', name: 'Eswatini' },
  { code: 'Ethiopia', name: 'Ethiopia' },
  { code: 'Fiji', name: 'Fiji' },
  { code: 'Finland', name: 'Finland' },
  { code: 'France', name: 'France' },
  { code: 'Gabon', name: 'Gabon' },
  { code: 'Gambia', name: 'Gambia' },
  { code: 'Georgia', name: 'Georgia' },
  { code: 'Germany', name: 'Germany' },
  { code: 'Ghana', name: 'Ghana' },
  { code: 'Greece', name: 'Greece' },
  { code: 'Grenada', name: 'Grenada' },
  { code: 'Guatemala', name: 'Guatemala' },
  { code: 'Guinea', name: 'Guinea' },
  { code: 'Guinea-Bissau', name: 'Guinea-Bissau' },
  { code: 'Guyana', name: 'Guyana' },
  { code: 'Haiti', name: 'Haiti' },
  { code: 'Honduras', name: 'Honduras' },
  { code: 'Hungary', name: 'Hungary' },
  { code: 'Iceland', name: 'Iceland' },
  { code: 'India', name: 'India' },
  { code: 'Indonesia', name: 'Indonesia' },
  { code: 'Iran', name: 'Iran' },
  { code: 'Iraq', name: 'Iraq' },
  { code: 'Ireland', name: 'Ireland' },
  { code: 'Israel', name: 'Israel' },
  { code: 'Italy', name: 'Italy' },
  { code: 'Ivory Coast', name: 'Ivory Coast' },
  { code: 'Jamaica', name: 'Jamaica' },
  { code: 'Japan', name: 'Japan' },
  { code: 'Jordan', name: 'Jordan' },
  { code: 'Kazakhstan', name: 'Kazakhstan' },
  { code: 'Kenya', name: 'Kenya' },
  { code: 'Kiribati', name: 'Kiribati' },
  { code: 'Kuwait', name: 'Kuwait' },
  { code: 'Kyrgyzstan', name: 'Kyrgyzstan' },
  { code: 'Laos', name: 'Laos' },
  { code: 'Latvia', name: 'Latvia' },
  { code: 'Lebanon', name: 'Lebanon' },
  { code: 'Lesotho', name: 'Lesotho' },
  { code: 'Liberia', name: 'Liberia' },
  { code: 'Libya', name: 'Libya' },
  { code: 'Liechtenstein', name: 'Liechtenstein' },
  { code: 'Lithuania', name: 'Lithuania' },
  { code: 'Luxembourg', name: 'Luxembourg' },
  { code: 'Madagascar', name: 'Madagascar' },
  { code: 'Malawi', name: 'Malawi' },
  { code: 'Malaysia', name: 'Malaysia' },
  { code: 'Maldives', name: 'Maldives' },
  { code: 'Mali', name: 'Mali' },
  { code: 'Malta', name: 'Malta' },
  { code: 'Marshall Islands', name: 'Marshall Islands' },
  { code: 'Mauritania', name: 'Mauritania' },
  { code: 'Mauritius', name: 'Mauritius' },
  { code: 'Mexico', name: 'Mexico' },
  { code: 'Micronesia', name: 'Micronesia' },
  { code: 'Moldova', name: 'Moldova' },
  { code: 'Monaco', name: 'Monaco' },
  { code: 'Mongolia', name: 'Mongolia' },
  { code: 'Montenegro', name: 'Montenegro' },
  { code: 'Morocco', name: 'Morocco' },
  { code: 'Mozambique', name: 'Mozambique' },
  { code: 'Myanmar', name: 'Myanmar' },
  { code: 'Namibia', name: 'Namibia' },
  { code: 'Nauru', name: 'Nauru' },
  { code: 'Nepal', name: 'Nepal' },
  { code: 'Netherlands', name: 'Netherlands' },
  { code: 'New Zealand', name: 'New Zealand' },
  { code: 'Nicaragua', name: 'Nicaragua' },
  { code: 'Niger', name: 'Niger' },
  { code: 'Nigeria', name: 'Nigeria' },
  { code: 'North Korea', name: 'North Korea' },
  { code: 'North Macedonia', name: 'North Macedonia' },
  { code: 'Norway', name: 'Norway' },
  { code: 'Oman', name: 'Oman' },
  { code: 'Pakistan', name: 'Pakistan' },
  { code: 'Palau', name: 'Palau' },
  { code: 'Palestine State', name: 'Palestine State' },
  { code: 'Panama', name: 'Panama' },
  { code: 'Papua New Guinea', name: 'Papua New Guinea' },
  { code: 'Paraguay', name: 'Paraguay' },
  { code: 'Peru', name: 'Peru' },
  { code: 'Philippines', name: 'Philippines' },
  { code: 'Poland', name: 'Poland' },
  { code: 'Portugal', name: 'Portugal' },
  { code: 'Qatar', name: 'Qatar' },
  { code: 'Romania', name: 'Romania' },
  { code: 'Russia', name: 'Russia' },
  { code: 'Rwanda', name: 'Rwanda' },
  { code: 'Saint Kitts and Nevis', name: 'Saint Kitts and Nevis' },
  { code: 'Saint Lucia', name: 'Saint Lucia' },
  { code: 'Saint Vincent and the Grenadines', name: 'Saint Vincent and the Grenadines' },
  { code: 'Samoa', name: 'Samoa' },
  { code: 'San Marino', name: 'San Marino' },
  { code: 'Sao Tome and Principe', name: 'Sao Tome and Principe' },
  { code: 'Saudi Arabia', name: 'Saudi Arabia' },
  { code: 'Senegal', name: 'Senegal' },
  { code: 'Serbia', name: 'Serbia' },
  { code: 'Seychelles', name: 'Seychelles' },
  { code: 'Sierra Leone', name: 'Sierra Leone' },
  { code: 'Singapore', name: 'Singapore' },
  { code: 'Slovakia', name: 'Slovakia' },
  { code: 'Slovenia', name: 'Slovenia' },
  { code: 'Solomon Islands', name: 'Solomon Islands' },
  { code: 'Somalia', name: 'Somalia' },
  { code: 'South Africa', name: 'South Africa' },
  { code: 'South Korea', name: 'South Korea' },
  { code: 'South Sudan', name: 'South Sudan' },
  { code: 'Spain', name: 'Spain' },
  { code: 'Sri Lanka', name: 'Sri Lanka' },
  { code: 'Sudan', name: 'Sudan' },
  { code: 'Suriname', name: 'Suriname' },
  { code: 'Sweden', name: 'Sweden' },
  { code: 'Switzerland', name: 'Switzerland' },
  { code: 'Syria', name: 'Syria' },
  { code: 'Taiwan', name: 'Taiwan' },
  { code: 'Tajikistan', name: 'Tajikistan' },
  { code: 'Tanzania', name: 'Tanzania' },
  { code: 'Thailand', name: 'Thailand' },
  { code: 'Timor-Leste', name: 'Timor-Leste' },
  { code: 'Togo', name: 'Togo' },
  { code: 'Tonga', name: 'Tonga' },
  { code: 'Trinidad and Tobago', name: 'Trinidad and Tobago' },
  { code: 'Tunisia', name: 'Tunisia' },
  { code: 'Turkey', name: 'Turkey' },
  { code: 'Turkmenistan', name: 'Turkmenistan' },
  { code: 'Tuvalu', name: 'Tuvalu' },
  { code: 'Uganda', name: 'Uganda' },
  { code: 'Ukraine', name: 'Ukraine' },
  { code: 'United Arab Emirates', name: 'United Arab Emirates' },
  { code: 'United Kingdom', name: 'United Kingdom' },
  { code: 'United States', name: 'United States' },
  { code: 'Uruguay', name: 'Uruguay' },
  { code: 'Uzbekistan', name: 'Uzbekistan' },
  { code: 'Vanuatu', name: 'Vanuatu' },
  { code: 'Vatican City', name: 'Vatican City' },
  { code: 'Venezuela', name: 'Venezuela' },
  { code: 'Vietnam', name: 'Vietnam' },
  { code: 'Yemen', name: 'Yemen' },
  { code: 'Zambia', name: 'Zambia' },
  { code: 'Zimbabwe', name: 'Zimbabwe' },
];
